import { reactive } from 'vue';

export const store = reactive({
    menuLogoSrc: '../img/menulogo.png',
    headerTitle: 'Are you ready for your next challenge?',
    arrowRightSrc: '../img/image-12.svg',
    arrowLeftSrc: '../img/arrowleft.svg',
    arrowLeftWhiteSrc: '../img/arrowleft-white.svg',
    arrowRightWhiteSrc: '../img/arrowright-white.svg',
    playBtnSrc: '../img/image-9.svg',
    playGreenSrc: '../img/play-green.svg',
    menuSearchSrc: '../img/search.svg',
    menuCartSrc: '../img/cart.svg',
    messageSrc: '../img/message.svg',
    expirienceImg: '../img/exprince.jpg',
    exprienceShapeImg: '../img/exprience-shape.png',
    okSrc: '../img/ok.svg',
    vectorBgSrc: '../img/Vector.png',
    vector2BgSrc: '../img/prontfolio-vector.png',
    featureLiveSrc: '../img/feature1.png',
    featureMonitorSrc: '../img/feature2.png',
    featureJoypadSrc: '../img/feature3.png',
    featureAwardsSrc: '../img/feature4.png',
    previewVideoStreamSrc: '../img/v-small1.png',
    playStreamSrc: '../img/play.svg',
    stream2Src: '../img/v-small2.png',
    virgoletteSrc: '../img/virgolette.svg',
    menuItems: [
        {
            name: 'Home',
            iconSrc: '../img/image.svg',
            id: '0',
        },
        {
            name: 'Pages',
            iconSrc: '../img/image.svg',
            id: '1',
        },
        {
            name: 'Tournament',
            id: '2',
        },
        {
            name: 'Shop',
            iconSrc: '../img/image.svg',
            id: '3',
        },
        {
            name: 'Blog',
            iconSrc: '../img/image.svg',
            id: '4',
        },
        {
            name: 'Contact',
            id: '5',
        },
    ],
    socialsSrc: ['../img/facebook.svg','../img/twitter.svg','../img/linkedin.svg','../img/instagram.svg'],
    gameLogos: ['../img/1.png','../img/2.png','../img/3.png','../img/4.png','../img/5.png','../img/6.png'],
    matchs: [
        {
            firstMatchSrc: '../img/t3.png',
            firstMatchCountry: 'Italy',
            firstGameName: 'Ninga Gaming',
            secondMatchSrc: '../img/t4.png',
            secondMatchCountry: 'India',
            secondGameName: 'Witch Gaming',
            title: 'PUBG Battelground',
            text: 'Nulla porttitor accumsan tincidunt. Vivamus magna justo, lacinia eget consecterum sed, convallis at tellus. Vivamus magna justo.',
            time: '10.45',
            date: '1st November, 2022',
            youtubeLogoSrc: '../img/youtube.svg',
            messageSrc: '../img/message-white.svg',
            id: '0',
        },
        {
            firstMatchSrc: '../img/t1.png',
            firstMatchCountry: 'Italy',
            firstGameName: 'King Gaming',
            secondMatchSrc: '../img/t2.png',
            secondMatchCountry: 'India',
            secondGameName: 'Witch Astro',
            title: "Assassin's Creed",
            text: 'Nulla porttitor accumsan tincidunt. Vivamus magna justo, lacinia eget consecterum sed, convallis at tellus. Vivamus magna justo.',
            time: '09.45',
            date: '1st November, 2022',
            youtubeLogoSrc: '../img/youtube-black.svg',
            messageSrc: '../img/message-black.svg',
            id: '1',
        },
        {
            firstMatchSrc: '../img/t5.png',
            firstMatchCountry: 'Italy',
            firstGameName: 'Dng Gaming',
            secondMatchSrc: '../img/t6.png',
            secondMatchCountry: 'India',
            secondGameName: 'Joker Gaming',
            title: 'Mortal Combat X',
            text: 'Nulla porttitor accumsan tincidunt. Vivamus magna justo, lacinia eget consecterum sed, convallis at tellus. Vivamus magna justo.',
            time: '08.45',
            date: '1st November, 2022',
            youtubeLogoSrc: '../img/youtube-black.svg',
            messageSrc: '../img/message-black.svg',
            id: '2',
        },
        {
            firstMatchSrc: '../img/t7.png',
            firstMatchCountry: 'Italy',
            firstGameName: 'Shark Gaming',
            secondMatchSrc: '../img/t8.png',
            secondMatchCountry: 'India',
            secondGameName: 'Krull Gaming',
            title: 'Call Of Deauty',
            text: 'Nulla porttitor accumsan tincidunt. Vivamus magna justo, lacinia eget consecterum sed, convallis at tellus. Vivamus magna justo.',
            time: '04.45',
            date: '1st November, 2022',
            youtubeLogoSrc: '../img/youtube-black.svg',
            messageSrc: '../img/message-black.svg',
            id: '3',
        },
    ],
    assassinSrc: '../img/protfolio1.png',
    soldierSrc: '../img/protfolio2.png',
    archerSrc: '../img/protfolio3.png',
    ninjaSrc: '../img/protfolio4.png',
    upcomingBgSrc: '../img/v-bg.png',
    upcomingCard1Src: '../img/m1.png',
    upcomingCard2Src: '../img/m2.png',
    upcomingCard3Src: '../img/m3.png',
    youtubeLogoBlackSrc: '../img/youtube-black.svg',
    messageLogoBlackSrc: '../img/message-black.svg',
    youtubeLogoGreenSrc: '../img/youtube-green.svg',
    messageLogoGreenSrc: '../img/message-green.svg',
    battles: [
        {
            imgSrc: '../img/m1.png',
            id: '0',
            date: '1st November, 2022',
            time: '09.45',
            name: 'Ninja Warrior Gaming',
        },
        {
            imgSrc: '../img/m2.png',
            id: '1',
            date: '1st November, 2022',
            time: '09.45',
            name: 'Witch Gaming',
        },
        {
            imgSrc: '../img/m3.png',
            id: '2',
            date: '1st November, 2022',
            time: '09.45',
            name: 'SkullG Gaming',
        },
    ],
    members: [
        {
            memberSrc: '../img/team1.png',
            fullname: 'Cristiano Messi',
            profession: 'CEO/Founder',
            id: '0',
        },
        {
            memberSrc: '../img/team2.png',
            fullname: 'Sergio Naymer',
            profession: 'Programmer',
            id: '1',
        },
        {
            memberSrc: '../img/team3.png',
            fullname: 'Antonela Roccuzzo',
            profession: 'Project Manager',
            id: '2',
        },
        {
            memberSrc: '../img/team4.png',
            fullname: 'Lionel Ramos',
            profession: 'Game Designer',
            id: '3',
        },
    ],
    testimonials: [
        {
            src: '../img/test1.png',
            id: '0',
        },
        {
            src: '../img/test2.png',
            id: '1',
        },
        {
            src: '../img/test3.png',
            id: '2',
        },
        {
            src: '../img/test4.png',
            id: '3',
        },
    ],
    articles: [
        {
            articleSrc: '../img/s1.png',
            starGreenSrc: '../img/starGreen.svg',
            starWhiteSrc: '../img/starWhite.svg',
            articleName: 'Asus Rog Strix A53',
            greenPrize: '$970.00',
            whitePrize: '$999.00',
            id: '0',
        },
        {
            articleSrc: '../img/s2.png',
            starGreenSrc: '../img/starGreen.svg',
            starWhiteSrc: '../img/starWhite.svg',
            articleName: 'Asus Rog Strix A53',
            greenPrize: '$970.00',
            whitePrize: '$999.00',
            id: '1',
            optionsIconSrc: ['../img/eye.svg','../img/cartSmall.svg','../img/heart.svg']
        },
        {
            articleSrc: '../img/s3.png',
            starGreenSrc: '../img/starGreen.svg',
            starWhiteSrc: '../img/starWhite.svg',
            articleName: 'Asus Rog Strix A53',
            greenPrize: '$970.00',
            whitePrize: '$999.00',
            id: '2',
        },
        {
            articleSrc: '../img/s4.png',
            starGreenSrc: '../img/starGreen.svg',
            starWhiteSrc: '../img/starWhite.svg',
            articleName: 'Asus Rog Strix A53',
            greenPrize: '$970.00',
            whitePrize: '$999.00',
            id: '3',
        },
    ],
    lastestNews: [
        {
            newSrc: '../img/b1.png',
            newName: 'Ninja Warrior Gaming',
            id: '0',
        },
        {
            newSrc: '../img/b2.png',
            newName: 'Gost Rider Retruns',
            id: '1',
        },
        {
            newSrc: '../img/b3.png',
            newName: 'Call of Deauty 4',
            id: '2',
        },
        {
            newSrc: '../img/b4.png',
            newName: 'Mortal Combat X',
            id: '3',
        },
    ]
})